### ISSUE TITLE
签名错误

### ISSUE THREAD

**Issue by purplecity** [yugasun/tezos-sign#2]
我生成一个操作hash。但是离线签名的时候出错了。报错私钥长度不对。可是我的私钥确定是正确的。

<img width="800" alt="tezos10" src="https://user-images.githubusercontent.com/38914615/52610877-e3611d80-2ebd-11e9-9d14-2415735180ed.png">
<img width="1165" alt="tezos11" src="https://user-images.githubusercontent.com/38914615/52610878-e3f9b400-2ebd-11e9-9af9-36ac969cbc4a.png">
<img width="999" alt="tezos12" src="https://user-images.githubusercontent.com/38914615/52610881-e3f9b400-2ebd-11e9-8b27-e00798ec1d26.png">

生成的操作hash按照https://medium.com/@bakenrolls/sending-multiple-transactions-in-one-batch-using-tezos-rpc-6cab3a21f254  这里的步骤我加了一个0x03

**Comment by yugasun** [comment]
@purplecity 你的私钥是如何生成的，正常的生成的私钥不含 `0x` 应该是 98位，但是就你截图来看，是错误的长度。

**Comment by purplecity** [comment]
我的私钥是在节点上(docker)命令行调用生成的(公私钥对) .  取secret_keys 这个文件中的拿得

<img width="910" alt="tezos13" src="https://user-images.githubusercontent.com/38914615/52619332-6002f480-2edc-11e9-927b-802cdfa13b54.png">

我 extract 私钥之后可行了。--谢谢
